dbms_project/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from aimals import views as aimals_views 
from lineage import views as lineage_views
from habitat import views as habitat_views
from health import views as health_views
from migration import views as migration_views
from transfers import views as transfers_views

from django.views.i18n import JavaScriptCatalog
urlpatterns = [
    
    path('admin/',admin.site.urls),
    #path('lhome/',lineage_views.ho,name='lhome'),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('',include('front.urls')),
    path('insert/',aimals_views.animals_insert,name='insert'),
    path('homepage/',include('front.urls')),
    path("homehabitat/",habitat_views.habitat_record,name="homehabitat"),
    path('habitatinsert/',habitat_views.habitat_create,name='habitatinsert.html'),
    path('update_health/<int:pk>/',health_views.health_update,name='update_health'),
    path('update_lineage/<int:pk>/',lineage_views.lineage_update,name='update_lineage'),
    #path('lhome/',lineage_views.line,name='lhome'),
    path('updatetransfer/<int:pk>/',transfers_views.transferupdate,name='updatetransfer'),
    path('update_migration/<int:pk>/',migration_views.migration_update,name='update_migration'),
    path('fauna/',aimals_views.fauna,name='fauna'),
    path('fauna/<int:pk>',aimals_views.animals_record,name='animal'),
    path('delete_fauna/<int:pk>',aimals_views.animals_delete,name='delete_fauna'),
    path('update_fauna/<int:pk>',aimals_views.animals_update,name='update_fauna'),
    path('searchfauna/',aimals_views.search_fauna,name='searchfauna'),
    path('update_habitat/<int:pk>',habitat_views.habitat_update,name='update_habitat'),
    path('searchhabitat/',habitat_views.search_habitat,name='searchhabitat'),
    path("homehabitat/<int:pk>",habitat_views.habitat_search,name="habitat"),
    path("delete_habitat/<int:pk>",habitat_views.habitat_Delete,name='delete_habitat'),
]   
admin.site.site_header="ABC Admin"
admin.site.site_title="ABC Admin"
admin.site.index_title="WELCOME TO THE ADMIN AREA"

front/urls.py
from django.urls import path
from . import views 
'''importing from the current directory'''
urlpatterns =[
    path('',views.home,name='front-home'),
  
    path('about/',views.about,name='front-about'),

    path('homepage/',views.hp,name='front-homepage'),
]

aimals/models.py
from django.db import models
from habitat.models import habitat
from datetime import date
class animals(models.Model):
    animal_id=models.BigIntegerField(primary_key=True)
    aname=models.CharField(max_length=40)
    sex=models.CharField(max_length=10)
    dob=models.DateField()
  
    age=models.IntegerField()
    specices=models.CharField(max_length=256)
    date_of_death=models.DateField(null=True,blank=True)
    date_of_arrival=models.DateField()
    description=models.CharField(max_length=255,null=True,blank=True)
    Habitat_id=models.ForeignKey(habitat,on_delete=models.SET_NULL, null=True,db_column='Habitat_id')
    last_updated=models.DateField(null=True)

    def __str__(self):
        return self.aname
    
    """
    def age(self):
        today = date.today()
        age = today.year - self.dob.year
        # Check if the birthday has already occurred this year
        if today < date(today.year, self.dob.month, self.dob.day):
            age -= 1
        return age 
    
    def save(self, *args, **kwargs):
        self.age = self.age()  # Calculate the age based on the dob field
        super().save(*args, **kwargs)"""

habitat/models.py
from django.db import models


    


class habitat(models.Model):
    Habitat_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    major_fauna = models.CharField(max_length=255, null=True, blank=True)
    area_covered = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    last_updated=models.DateField(null=True)

    def __str__(self):
        return self.name

habitat/forms.py
from django import forms
from .models import habitat

class habitatinsert(forms.ModelForm):
    class Meta:
        model = habitat
        fields = ['name', 'type', 'description', 'major_fauna', 'area_covered', 'last_updated']
        labels = {
            'name': 'Name',
            'type': 'Type',
            'description': 'Description',
            'major_fauna': 'Major Fauna',
            'area_covered': 'Area Covered',
            'last_updated': 'Last Updated',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'major_fauna': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Major Fauna'}),
            'area_covered': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Area Covered'}),
            'last_updated': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Last Updated'}),
        }

habitat/views.py
from django.shortcuts import render,redirect
from .forms import habitatinsert
from django.contrib import messages
from django.contrib import admin
from .models import habitat
from django.shortcuts import get_object_or_404
admin.site.register(habitat)
def habitat_create(request):
    if request.method == 'POST':
        form = habitatinsert(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data inserted successfully!')
            return redirect('homehabitat')
    else:
        form = habitatinsert()
        #messages.error(request, 'Data inserted unsuccessfully!')
    return render(request, 'habitatinsert.html',{'form':form})

def homehabitat(request):
    return render(request,'homehabitat.html',{})

def habitat_search(request,pk):
    
        habitats_record=get_object_or_404(habitat,pk=pk)
        return render(request, 'habitat_record.html',{'habitats_record':habitats_record})

def habitat_record(request):
    habitat_list=habitat.objects.all()
    return render(request, 'homehabitat.html',{'habitat_list':habitat_list})

def habitat_Delete(request,pk):
    delete_it =get_object_or_404(habitat,pk=pk)
    delete_it.delete()
    messages.success(request,"Record deleted ..")
    return redirect('homehabitat')

def habitat_update(request,pk):
    current_record=get_object_or_404(habitat,pk=pk)
    form=habitatinsert(request.POST or None,instance=current_record)
    if form.is_valid():
        form.save()
        messages.success(request,"Record updated..")
        return redirect('homehabitat')
    return render(request, 'update_habitat.html',{'current_record':current_record,'form':form})
def search_habitat(request):
    if request.method =='POST':
        searched=request.POST['searched']
        filtered=request.POST['filter1']
        if filtered=='name':
            results=habitat.objects.filter(name__contains=searched)
            return render(request, 'searchhabitat.html',{'searched':searched, 'results':results})
        elif filtered=='major_fauna':
            results=habitat.objects.filter(major_fauna__contains=searched)
            return render(request, 'searchhabitat.html',{'searched':searched, 'results':results})
    else:
       
        return render(request, 'searchfauna.html',{})

habitat/templates/habitat_record.html
<!DOCTYPE html>
{%load static%}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        {%load static %}
        <link rel="stylesheet" href="{%static 'C://Users//kulu1//Desktop//dbms_project//static//animals.css'%}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"rel ="stylesheet" >
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    </head>
    
    <body>
      <div class="row">
      <div class="col-12">

        
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ABC Sanctuary</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if user.is_authenticated %}
              `<li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/logout">logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/login">Staff Login</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Fauna
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/fauna/">Search</a></li>
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/insert/
                    
                    ">Insert Data</a></li>
                 
                </ul>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Habitat
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/homehabitat/">Search</a></li>
                  
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/habitatinsert/">Insert Data</a></li>
            
                </ul>
              </li>
            </ul>  
          </div>
         
        </div>
      </nav>
      </div>
      </div>
      <div class="container mt-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{habitats_record.name}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{habitats_record.type}}</h6>
              <p class="card-text">{{habitats_record.description}}</p>
              Major-Fauna:{{habitats_record.major_fauna}}
              <br>
              
              <a href="{% url 'delete_habitat' habitats_record.Habitat_id%}" class="sm-btn btn-danger">Delete</a>
              <a href="{% url 'update_habitat' habitats_record.Habitat_id%}" class="sm-btn btn-danger">update</a>
              </div>        
          </div>
      </div>
      
     
      

        
</body>
</html>

habitat/templates/habitatinsert.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        {%load static %}
        <link rel="stylesheet" href="{%static 'C:\Users\kulu1\Desktop\dbms_project\static\css\page.css'%}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"rel ="stylesheet" >
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    </head>
    
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ABC Sanctuary</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if user.is_authenticated %}
              `<li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/logout">logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/login">Staff Login</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Fauna
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/fauna/">Search</a></li>
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/insert/
                    
                    ">Insert Data</a></li>
           
                </ul>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Habitat
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/homehabitat/">Search</a></li>
                  
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/habitatinsert/">Insert Data</a></li>
                
                </ul>
              </li>
            </ul>


            
          </div>
        </div>
      </nav>
      {% if messages %}
      {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
      {% endfor %}
  {% endif %}
      
      <div class="container mt-4">
        <form method="POST" action="">
            {% csrf_token %}
        
        <div class="form-group">
          <label for="id_aname">Name:</label>
     
          <div class="col-sm-10">
          <input type="text" name="name" class="form-control" value=""/>
          </div>
        </div>
        
        
        
       
        
        
        
        <div class="form-group">
          <label for="id_Type">Type:</label>
          <div class="col-sm-10">
            <input type="text" name="type" class="form-control" value=""/>
            </div>
        </div>
        
        
        
        
        <div class="form-group">
          <label for="id_last_updated">Description:</label>
          
          <textarea class="form-control" id="Description" rows="3"></textarea>
            
        </div>

        <div class="form-group">
          <label for="major_Fauna">Major Fauna</label>
          <div class="col-sm-10">
            <input type="text" name="habitat_id" class="form-control" value=""/>
            </div>
        </div>
        <div class="form-group">
          <label for="area_covered">Area covered</label>
          <div class="col-sm-10">
            <input type="number" name="habitat_id" class="form-control" value=""/>
            </div>
        </div>
        
        <div class="form-group">
          <label for="id_last_updated">Last Updated:</label>
          <div class="col-sm-10">
            <input type="date" name="last_updated" class="form-control" value=""/>
            </div>
        </div>
        
        <div class ="container mt-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        
        
      </form>
    </div>
        
   
</body>
</html>

habitat/templates/homehabitat.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        {%load static %}
        <link rel="stylesheet" href="{%static 'C:\Users\kulu1\Desktop\dbms_project\static\css\page.css'%}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"rel ="stylesheet" >
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    </head>
    
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ABC Sanctuary</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if user.is_authenticated %}
              `<li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/logout">logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/login">Staff Login</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Fauna
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/fauna/">Search</a></li>
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/insert/
                    
                    ">Insert Data</a></li>
           
                </ul>
              </li>
             
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Habitat
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/homehabitat/">Search</a></li>
                  
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/habitatinsert/">Insert Data</a></li>
                
                </ul>
              </li>
            </ul>


            
          </div>
        </div>
      </nav>
      {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
        {% endfor %}
    {% endif %}
      <div class="row">
        <div class="col-12 mt-4 ms-4">
          <form class="d-flex" method="POST" action="{%url 'searchhabitat'%}">
            {% csrf_token %}
            <input class="form-control-lg me-2" type="search" placeholder="Search_by" aria-label="Search" name="searched">
            <select class="form-select-sm me-2" aria-label="Filter" name="filter1">
              <option selected>Search by...</option>
              <option value="name">Name</option>
              <option value="specices">major_fauna</option>
              
              
             
            </select>
            <button class="btn btn-outline-secondary" type="submit">Search</button>
          </form>
          <div class="my-custom-row">
            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 ms-md-auto mt-4  ">
          <table class="table table-dark table-striped">
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">name</th>
                <th scope="col">Type</th>
                <th scope="col">major_fauna</th>
                <th scope="col">Area_covered</th>
                <th scope="col">last_updated</th>
               
  
  
              </tr>
            </thead>
            <tbody>
              {%if habitat_list %}
           
                {% for habitat in habitat_list %}
                <tr>
                  <td><a href="{%url 'habitat' habitat.Habitat_id%}">{{habitat.Habitat_id}}</a></td>
                  <td>{{habitat.name}}</td>
                  <td>{{habitat.type}}</td>
                  <td>{{habitat.major_fauna}}</td>
                  <td>{{habitat.area_covered}}</td>
                  <td>{{habitat.last_updated}}</td>
                
                </tr>
                 
                {% endfor %}
              
              {% endif %}  
  
  
              
            </tbody>
          </table>
          
        </div>
      </div>

        
    
</body>
</html>